name: Code checks and S3/EC2 deployment

on:
  push:
    branches:
      - main

jobs:
  code-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Pylint check
        run: pylint lambda_function.py

      - name: Flake8 check
        run: flake8 lambda_function.py

      - name: Bandit check
        run: bandit -r lambda_function.py

      - name: Upload code coverage
        uses: codecov/codecov-action@v1.1.0
        with:
          file: coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy-s3-ec2:
    runs-on: ubuntu-latest
    needs: code-checks
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create S3 bucket and EC2 instance
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: python create_s3_ec2.py
