name: Code checks and S3/EC2 deployment

on:
  push:
    branches:
      - main

jobs:
  code-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and Python
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install pylint
        run: pip install pylint

      - name: Pylint check
        run: pylint lambda_function.py

      - name: Install flake8
        run: pip install flake8

      - name: Flake8 check
        run: flake8 lambda_function.py

      - name: Install bandit
        run: pip install bandit
        
      - name: Bandit check
        run: bandit -r lambda_function.py


      - name: Upload code coverage
        uses: codecov/codecov-action@v1.1.0
        with:
          file: coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Save pylint score as environment variable
        id: pylint-score
        run: echo "::set-env name=PYLINT_SCORE::$(pylint --output-format=text lambda_function.py | awk '/Your code has been rated at/ { print $9 }')"
        shell: bash

  deploy-s3-ec2:
    runs-on: ubuntu-latest
    needs: code-checks
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and Python
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Create S3 bucket and EC2 instance
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: python create_s3_ec2.py
